AllCops:
  Exclude:
   - 'bin/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - '**/Gemfile'
   - '**/Rakefile'
   - 'spec/spec_helper.rb'
   - 'spec/rails_helper.rb'
   - 'spec/support/**/*'
   - 'node_modules/**/*'
   - 'app/views/**/*'

Rails:
 Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal